[DEV-6] Create New Workout Page UI
jpoist97/GainChanger pull request #14
Opened 2020-11-04 00:32 UTC by ctperry0301

![Simulator Screen Shot - iPhone 11 - 2020-11-03 at 16 11 07](https://user-images.githubusercontent.com/15805074/98055280-f33b3680-1df1-11eb-94a8-9854a095bde5.png)

2020-11-04 03:58 UTC, finlaylp approved these changes, later dismissed
Solid

2020-11-04 03:58 UTC, finlaylp commented on components/workouts/CreateWorkout.jsx
> +          onChangeText={() => setName(name)}
Shouldn't name be a parameter here

2020-11-04 07:03 UTC, rohithdara approved these changes, later dismissed
looks good to me

2020-11-04 07:15 UTC, jpoist97 requested changes
Current code looks good, I left a question for Shriya about the design of this page, and then the only thing I think is missing from here is that "sep x reps" list of components which would go where you commented about set details component

2020-11-04 07:15 UTC, jpoist97 commented on components/utils/FinishButton.jsx
> +  const Buttontext = styled.Text`
nit: Move this outside of the FInishButton function since it doesn't use props

2020-11-04 07:15 UTC, jpoist97 commented on components/workouts/CreateWorkout.jsx
> +          maxLength={40}
Should we make this ~15 chars, I think that's about how many will fit on two lines of the workout cards

2020-11-04 07:15 UTC, jpoist97 commented on components/workouts/CreateWorkout.jsx
> +      {/* This is where a list of set workout details components will go */}
This won't be set workout details components anymore right? This will be those "set x reps" components which I think should be a part of this task

2020-11-04 07:15 UTC, jpoist97 commented on components/workouts/Workouts.jsx
> +  return ( // This allows you to access 2 different pages on same navigation tab. (i.e. Workouts)
@shriyan44 is this the functionality we wanted here?, also if it is I think we should include a back button too.

2020-11-04 18:27 UTC, ctperry0301 commented on components/workouts/CreateWorkout.jsx
> +          onChangeText={() => setName(name)}
yup

2020-11-04 20:11 UTC, ctperry0301 commented
![ezgif com-gif-maker](https://user-images.githubusercontent.com/15805074/98162858-cd1ba200-1e96-11eb-9ce8-b4c0f37ab913.gif)

2020-11-05 00:13 UTC, finlaylp approved these changes, later dismissed

2020-11-05 18:29 UTC, jpoist97 reviewed
Looks good, just the small comment about the no-shadow thing. Also I prefer the textbox to keep the underline but that's just my preference (@shriyan44)

2020-11-05 18:29 UTC, jpoist97 commented on components/home/WorkoutContainer.jsx
> +/* eslint-disable */
I know this is giving linting issues but rohith is changing this component so this might create unnecessary merge conflicts

2020-11-05 18:29 UTC, jpoist97 commented on components/workouts/CreateWorkout.jsx
> +/* eslint-disable react/prop-types, no-shadow */
I think this is an important eslint check, I don't think we should disable this. i'll make a comment on how you can fix it

2020-11-05 18:29 UTC, jpoist97 commented on components/workouts/CreateWorkout.jsx
> +          onChangeText={(name) => setName(name)}
To fix the linting rename this to something else. e.g. "newName"

2020-11-06 04:02 UTC, jpoist97 approved these changes

2020-11-06 04:52 UTC, merged