Fix Cycle bug and update selected cycle in firebase
jpoist97/GainChanger pull request #54
Opened 2021-01-22 20:05 UTC by jpoist97

Fixed bug where cycles would not show up after reloading app. Also added functionality so that you can not select a cycle and it's updated in firebase.

2021-01-23 06:53 UTC, ctperry0301 commented on components/Home/Home.jsx
>    let cycleDetails;
You will get an index undefined error if you try to click on a left or right arrow on the home page if a cycle isn't set

2021-01-23 06:56 UTC, ctperry0301 commented on components/Home/Home.jsx
>    let cycleDetails;
> You will get an index undefined error if you try to click on a left or right arrow on the home page if a cycle isn't set

Im also getting the same error if I try to create a cycle while not having a cycle currently selected (new account).

2021-01-23 07:03 UTC, ctperry0301 requested changes
I dont think this code is working as expected for me, The cycles arent getting loaded in for me when I try and test it.

2021-01-25 18:55 UTC, jpoist97 commented
Thanks for catching that Cole, I forgot to test making a new account. All the bugs should be fixed now

2021-01-25 19:19 UTC, ctperry0301 approved these changes
Good Stuff!

2021-01-25 19:22 UTC, merged